/** Help-centre content inserted once, when help_articles is empty. */
export const HELP_ARTICLES = [
  { category: 'Finding a Room', title: 'How to search for rooms in a specific city', content: 'To search for a room in a specific city, go to the homepage and use the search bar. Enter the city name and click search. You can also use the "City" filter on the properties page to narrow down your results.', is_popular: true, read_time: 3 },
  { category: 'Finding a Room', title: 'Search tips for better results', content: 'Use the filters on the side of the property list to narrow down by budget, room type (shared/private), and amenities. Try nearby areas as well as the main city name.', is_popular: false, read_time: 3 },
  { category: 'Finding a Room', title: 'What to look for during a property visit', content: 'When visiting a room, check for proper ventilation, water supply, and mobile network strength. Ask the owner about guest policies, curfew times (if any), and how electricity bills are calculated.', is_popular: false, read_time: 6 },
  { category: 'Bookings', title: 'Understanding the booking process', content: 'Once you find a property you like, click "View Details" and then "Reserve This Room". Choose your move-in date and lease duration and send the request. The owner reviews it and confirms; you are then shown the owner\'s contact details to arrange the move-in. No payment is taken on the website.', is_popular: true, read_time: 5 },
  { category: 'Bookings', title: 'What happens after I send a booking request?', content: 'The owner receives your request with your name, email and phone number. When they accept, the booking shows as "confirmed" in your dashboard along with the owner\'s phone number. If they decline, you will see the reason and can request another room.', is_popular: false, read_time: 3 },
  { category: 'Safety & Trust', title: 'How to verify a property before booking', content: 'We recommend visiting the property in person before paying any deposit. Never pay a deposit before seeing the room and meeting the owner. Check the host reviews and ratings on the listing page.', is_popular: false, read_time: 4 },
  { category: 'Safety & Trust', title: 'How to report a fraudulent listing', content: 'If a listing seems suspicious or an owner asks for payment before a visit, contact our support team immediately through the Contact page and mention the property title. We investigate every report.', is_popular: false, read_time: 5 },
  { category: 'Payments & Pricing', title: 'How are rent and deposit paid?', content: 'Rent and the security deposit are paid directly to the owner after you have visited the property and both parties agree. Sasta Room does not collect payments on the website at this time.', is_popular: true, read_time: 4 },
  { category: 'Payments & Pricing', title: 'Understanding service charges', content: 'The rent shown on the listing is usually inclusive of basic maintenance. Some owners charge extra for electricity or water meter readings. Always confirm the full breakdown with the owner before moving in.', is_popular: false, read_time: 4 },
  { category: 'Listing a Property', title: 'How to list your property', content: 'Register as a Room Owner, open "List Your Property", fill in the details, add amenities and upload clear photos. Your listing is reviewed by our team and goes live once approved, usually within 24 hours.', is_popular: true, read_time: 4 },
  { category: 'Listing a Property', title: 'How to upload photos for your listing', content: 'Clear, high-quality photos increase your chances of getting tenants. Upload at least 5 photos showing the bedroom, bathroom, and common areas. Photos are automatically resized, so you can upload straight from your phone.', is_popular: false, read_time: 3 },
  { category: 'Listing a Property', title: 'How to handle tenant requests', content: 'Booking requests appear in your Owner Dashboard with the tenant\'s contact details. Reply quickly — accept the request to share your phone number with the tenant, or decline it with a short reason.', is_popular: false, read_time: 4 },
  { category: 'Account & Profile', title: 'How to update my phone number?', content: 'Your phone number is shared with owners when you request a booking, so keep it current. Contact support through the Contact page to update it and we will change it for you.', is_popular: false, read_time: 2 },
  { category: 'Account & Profile', title: 'Deleting your Sasta Room account', content: 'To delete your account, contact our support team through the Contact page. This action is permanent and removes all your data, including booking history and active listings.', is_popular: false, read_time: 4 },
];
